SELECT * FROM customer_shopping limit 10;
SHOW COLUMNS FROM customer_shopping;

ALTER TABLE customer_shopping 
CHANGE `ï»¿Customer ID` customer_id INT;

-- Q1. What is the total revenue generated by male vs. female customers?
select Gender, SUM(`Purchase Amount (USD)`) as revenue
from customer_shopping
group by Gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT `customer_id`, `Purchase Amount (USD)`
FROM customer_shopping
WHERE `Discount Applied` = 'Yes'
  AND `Purchase Amount (USD)` >= (
      SELECT AVG(`Purchase Amount (USD)`)
      FROM customer_shopping
  );
  
ALTER TABLE customer_shopping 
CHANGE `Purchase Amount (USD)` purchase_amount_usd DECIMAL(10,2),
CHANGE `Discount Applied` discount_applied VARCHAR(5);

-- Q3. Which are the top 5 products with the highest average review rating?
select `Item Purchased`, round(avg(`Review Rating`),2) as "Average Product Rating"
from customer_shopping
group by `Item Purchased`
order by avg(`Review Rating`) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select `Shipping Type`, 
ROUND(AVG(purchase_amount_usd),2)
from customer_shopping
where `Shipping Type` in ('Standard','Express')
group by `Shipping Type`;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT `Subscription Status`,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount_usd),2) AS avg_spend,
       ROUND(SUM(purchase_amount_usd),2) AS total_revenue
FROM customer_shopping
GROUP BY `Subscription Status`
ORDER BY Total_revenue,avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT `Item Purchased`,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_shopping
GROUP BY `Item Purchased`
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, `Previous Purchases`,
CASE 
    WHEN `Previous Purchases` = 1 THEN 'New'
    WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer_shopping)
select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT `Category`,
           `Item Purchased`,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY `Category` ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_shopping
    GROUP BY `Category`, `Item Purchased`
)
SELECT item_rank,`Category`, `Item Purchased`, total_orders
FROM item_counts
WHERE item_rank <=3;
 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT `Subscription Status`,
       COUNT(customer_id) AS repeat_buyers
FROM customer_shopping
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(previous_purchases) AS total_revenue
FROM customer_shopping
GROUP BY age_group
ORDER BY total_revenue DESC;